
# PHP + NGINX Container #----------------------------------
laravel5:
#  image: laradock/phpnginx:latest
  image: tkcdocker/laravel5
  container_name: laravel5
  ports:
    - "80:80"
  volumes:
    - ./settings/nginx:/etc/nginx/sites-available
    - ./laravel/:/var/www
    - ./logs/nginx:/var/log/nginx
  links:
    - mysql
    - mysqltesting
    - redis
  privileged: true
  extra_hosts:
    - "laravel.dev:xxx.xxx.xxx.xxx"


# MySQL Container #----------------------------------------
mysql:
  image: laradock/mysql:latest
  container_name: mysql
  ports:
    - "3306:3306"
  volumes_from:
    - data
#  volumes:
#    - ./logs/mysql:/var/log/mysql
  environment:
    MYSQL_DATABASE: homestead
    MYSQL_USER: homestead
    MYSQL_PASSWORD: secret
  privileged: true


# MySQL Container #----------------------------------------
mysqltesting:
  image: laradock/mysql:latest
  container_name: mysqltesting
  ports:
    - "3307:3306"
  volumes_from:
    - data
#  volumes:
#    - ./logs/mysql-testing:/var/log/mysql
  environment:
    MYSQL_DATABASE: homestead
    MYSQL_USER: homestead
    MYSQL_PASSWORD: secret
  privileged: true


# Redis Container #----------------------------------------
redis:
  image: laradock/redis:latest
  container_name: redis
  ports:
    - "6379:6379"
#  volumes_from:
#    - data
  volumes:
    - ./logs/redis:/var/log/redis
  restart: always
  privileged: true


# Data Volume Container #----------------------------------
data:
  image: laradock/data:latest
  container_name: data
  volumes:
    - /var/lib/mysql
    - /var/lib/redis


# Beanstalkd Container #-----------------------------------
# beanstalkd:
#   image: laradock/beanstalkd:latest
#   container_name: beanstalkd
#   ports:
#     - "11300:11300"
#   privileged: true

#----------------------------------------------------------
